### ISSUE TITLE
Effect not working when explorer is first opened, have to click on desktop to get it to work. 

### ISSUE THREAD

**Issue by Landreou** [Maplespe/ExplorerBlurMica#75]
When I open explorer, the effect doesn’t take place, I have to click on the desktop to make it work.
Just opened
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/153847080/7d9dca21-2eaa-4d24-97b7-036decf996ca)
Once clicked on the desktop
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/153847080/d8da54e0-01af-4f4b-9d50-c3ef7907f8f0)
my settings (this issue happens on every setting)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/153847080/e2fbffff-07d8-4f32-bad3-aad3b88ed956)

thank you

**Comment by tiger-git2022** [comment]
do you use startallback?

**Comment by Landreou** [comment]
Hello, No just use ExplorerBlurMica

**Comment by shprd95** [comment]
i have exactly the same issue, the blur is not applying when opening the explorer, i have to click somewhere else and then go back to make it appear

**Comment by Maplespe** [comment]
This issue has been resolved in the new version Please check.

**Comment by Veriiix** [comment]
I am still facing issues while using it alongside with startallback. When opening download folder through my browser i get a white bar on the bottom of my explorer and after every system reboot there is a black bar on top of the explorer window
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/77591428/66930273-d81a-424a-8795-928f3e1761a6)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/77591428/677d686e-c2f4-440a-88d6-d6dea0d7b74c)
